name: Build YAIIII APK

on:
  workflow_dispatch:
  push:
    branches:
      - principal
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permiso a Gradle
        run: chmod +x ./gradlew

      - name: Compilar APK
        run: ./gradlew assembleDebug

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: YAIIII-APK-debug
          path: app/build/outputs/apk/debug/*.apk
