
name: Build YAIIII APK

on:
  workflow_dispatch:
  push:
    branches:
      - principal
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Ver archivos iniciales
        run: ls -la

      - name: Descomprimir proyecto YAIIII
        run: unzip YAIIII_APK_V1_proyecto_android.zip -d proyecto

      - name: Ver contenido del proyecto
        run: find proyecto -maxdepth 4 -type f

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7

      - name: Compilar APK
        working-directory: proyecto/YAIIII_APK_V1
        run: gradle assembleDebug --stacktrace

      - name: Buscar APK generado
        run: find proyecto -name "*.apk" -type f

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: YAIIII-APK-debug
          path: proyecto/YAIIII_APK_V1/app/build/outputs/apk/debug/*.apk
